;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = #282A2E
background-alt = #373B41
foreground = #C5C8C6
primary = #F0C674
secondary = #8ABEB7
alert = #A54242
disabled = #707880

[bar/example]
width = 100%
height = 20pt
radius = 6
bottom = false

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-top = 10pt
border-left = 8pt
border-right = 8pt
border-color = #00000000

padding-left = 0
padding-right = 1

module-margin = 0


#separator = |
#separator-foreground = ${colors.disabled}

font-0 = monospace;2
font-1 = "Symbols Nerd Font:size=12;2"
font-2 = "Symbols Nerd Font:size=20;4"

modules-left = apps APPS_TO_DATE_ARROW  date DATE_TO_TIME_ARROW time TIME_TO_CPU_ARROW cpu CPU_TO_MEMORY_ARROW memory MEMORY_TO_TITLE_ARROW title TITLE_TO_BAR_ARROW
modules-center = ewmh
modules-right = tray LAYOUT_TO_SYSYTAY_ARROW bspwm-layout VOLUME_TO_LAYOUT_ARROW volume NERD_TO_VOLUME_ARROW nerddictation UPDATES_TO_NERD_ARROW updatecheck NETWORK_TO_UPDATES_ARROW nmcli SSH_TO_NETWORK_ARROW ssh POWER_TO_SSH_ARROW power

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

; override-redirect = true

; This module is not active by default (to enable it, add it to one of the
; modules-* list above).
; Please note that only a single tray can exist at any time. If you launch
; multiple bars with this module, only a single one will show it, the others
; will produce a warning. Which bar gets the module is timing dependent and can
; be quite random.
; For more information, see the documentation page for this module:
; https://polybar.readthedocs.io/en/stable/user/modules/tray.html
[module/systray]
type = internal/tray

format-margin = 8pt
tray-spacing = 16pt


#####################
##Modules
#####################
#[module/apps]
#	type = custom/script
#	exec = /home/chris/.config/bspwm/scripts/OpenFlexOS_Applications.sh
#	click-left = /home/chris/.config/bspwm/scripts/OpenFlexOS_Applications.sh -d
#	click-right = /home/chris/.config/bspwm/scripts/OpenFlexOS_Applications.sh -r
#	format-foreground = #000000
#	format-background = #EA999C
#		[module/APPS_TO_DATE_ARROW]
#		type=custom/text
#		content = 
#		content-foreground = #EA999C
#		content-background = #A6E3A1
#		content-font = 3


[module/date]
	type = internal/date
	date = %a %d-%m-%Y
	label =  %date%
	format-foreground = #000000
	format-background = #A6E3A1
		[module/DATE_TO_TIME_ARROW]
		type=custom/text
		content = 
		content-foreground = #A6E3A1
		content-background = #EA999C
		content-font = 3


[module/time]
	type = internal/date
	interval = 1.0
	time = %I:%M:%S
	label =  %time%
	format-foreground = #000000
	format-background = #EA999C
		[module/TIME_TO_CPU_ARROW]
		type=custom/text
		content = 
		content-foreground = #EA999C
		content-background = #A6E3A1
		content-font = 3

[module/cpu]
	type = internal/cpu
	label =  %percentage%%
	interval = 0.5
	format-foreground = #000000
	format-background = #A6E3A1
		[module/CPU_TO_MEMORY_ARROW]
		type=custom/text
		content = 
		content-foreground = #A6E3A1
		content-background = #EA999C
		content-font = 3


[module/memory]
	type = internal/memory
	interval = 0.5
	label =  %percentage_used%%
	format-foreground = #000000
	format-background = #EA999C
		[module/MEMORY_TO_TITLE_ARROW]
		type=custom/text
		content = 
		content-foreground = #EA999C
		content-background = #A6E3A1
		content-font = 3


[module/title]
	type = internal/xwindow
	label = %class% %title%
	label-empty = None
	label-maxlen = 20
	format-foreground = #000000
	format-background = #A6E3A1
		[module/TITLE_TO_BAR_ARROW]
		type=custom/text
		content = 
		content-foreground = #A6E3A1
		content-background =
		content-font = 3

[module/ewmh]
type = internal/xworkspaces
label-active-background = #3f3f3f
label-occupied-underline = #555555

[module/tray]
	type = internal/tray
	format-margin = 8px
	tray-spacing = 8px
	tray-padding = 2px
	tray-size = 70%
	format-background = #EA999C
		[module/LAYOUT_TO_SYSYTAY_ARROW]
		type=custom/text
		content = 
		content-foreground = #A6E3A1
		content-background = #EA999C
		content-font = 3

[module/bspwm-layout]
	type = custom/script
	exec = /home/chris/.config/bspwm/scripts/bspwm-layout.sh
	interval = 1
	label = %output%
	format-foreground = #000000
	format-background = #A6E3A1
		[module/VOLUME_TO_LAYOUT_ARROW]
		type=custom/text
		content = 
		content-foreground = #EA999C
		content-background = #A6E3A1
		content-font = 3

[module/volume]
	type = custom/script
	exec = /home/chris/.config/bspwm/scripts/OpenFlexOS_Volume.sh
	click-left = /home/chris/.config/bspwm/scripts/OpenFlexOS_Volume.sh -u
	click-right = /home/chris/.config/bspwm/scripts/OpenFlexOS_Volume.sh -d
	click-middle = /home/chris/.config/bspwm/scripts/OpenFlexOS_Volume.sh -m
	format-foreground = #000000
	format-background = #EA999C
		[module/NERD_TO_VOLUME_ARROW]
		type=custom/text
		content = 
		content-foreground = #A6E3A1
		content-background = #EA999C
		content-font = 3

[module/nerddictation]
	type = custom/script
	exec = /home/chris/.config/bspwm/scripts/OpenFlexOS_NerdDictation.sh
	click-left = /home/chris/.config/bspwm/scripts/OpenFlexOS_NerdDictation.sh -s
	click-right = /home/chris/.config/bspwm/scripts/OpenFlexOS_NerdDictation.sh -S
	format-foreground = #000000
	format-background = #A6E3A1
		[module/UPDATES_TO_NERD_ARROW]
		type=custom/text
		content = 
		content-foreground = #EA999C
		content-background = #A6E3A1
		content-font = 3

[module/updatecheck]
	type = custom/script
	exec = /home/chris/.config/bspwm/scripts/OpenFlexOS_UpdateCheck.sh
	click-left = /home/chris/.config/bspwm/scripts/OpenFlexOS_UpdateCheck.sh -u
	click-right = /home/chris/.config/bspwm/scripts/OpenFlexOS_UpdateCheck.sh -v
	format-foreground = #000000
	format-background = #EA999C
		[module/NETWORK_TO_UPDATES_ARROW]
		type=custom/text
		content = 
		content-foreground = #A6E3A1
		content-background = #EA999C
		content-font = 3


[module/nmcli]
	type = custom/script
	exec = /home/chris/.config/bspwm/scripts/OpenFlexOS_Network.sh
	click-left = /home/chris/.config/bspwm/scripts/OpenFlexOS_Network.sh -d
	click-right = /home/chris/.config/bspwm/scripts/OpenFlexOS_Network.sh -r
	format-foreground = #000000
	format-background = #A6E3A1
#		[module/SSH_TO_NETWORK_ARROW]
#		type=custom/text
#		content = 
#		content-foreground = #EA999C
#		content-background = #A6E3A1
#		content-font = 3

#[module/ssh]
#	type = custom/script
#	exec = echo "SSH"
#	click-left = /home/chris/.config/bspwm/scripts/OpenFlexOS_SSH.sh -d
#	click-right = /home/chris/.config/bspwm/scripts/OpenFlexOS_SSH.sh -r
#	format-foreground = #000000
#	format-background = #EA999C
#		[module/POWER_TO_SSH_ARROW]
#		type=custom/text
#		content = 
#		content-foreground = #A6E3A1
#		content-background = #EA999C
#		content-font = 3

#[module/power]
#	type = custom/script
#	exec = /home/chris/.config/bspwm/scripts/OpenFlexOS_Power.sh
#	click-left = /home/chris/.config/bspwm/scripts/OpenFlexOS_Power.sh -d
#	click-right = /home/chris/.config/bspwm/scripts/OpenFlexOS_Power.sh -r
#	format-foreground = #000000
#	format-background = #A6E3A1

occupied-scroll = true

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
