#! /bin/sh

# See file autostart.sh for applicatiosn that start at login
source autostart.sh

### For singal wallpaper
# Create a config file if it dont exists, saves the wallpaper the user selected and applies the wallpaper at login
CONFIG_FILE="/home/$USER/.config/$DESKTOP_SESSION/.selected_wallpaper"

# Check if the configuration file exists and is not empty
if [ -s "$CONFIG_FILE" ]; then
  # Read the saved wallpaper path
  SELECTED_WALLPAPER=$(cat "$CONFIG_FILE")
  # Apply the wallpaper using feh
  feh --bg-scale "$SELECTED_WALLPAPER" &
fi

## For multi wallpaper
# Define the wallpaper configuration file
CONFIG_FILE="$HOME/.config/qtile/.multi_selected_wallpaper"
# Check if the configuration file exists and is not empty
if [[ -s "$CONFIG_FILE" ]]; then
    # Create an array to store wallpaper arguments
    wallpaper_args=()

    # Read each line of the file
    while IFS='=' read -r monitor wallpaper; do
        # Ensure the line is not empty and the wallpaper file exists
        if [[ -n "$monitor" && -n "$wallpaper" && -f "$wallpaper" ]]; then
            # Store the wallpaper arguments for feh
            wallpaper_args+=("--bg-scale" "$wallpaper")
        fi
    done < "$CONFIG_FILE"

    # Apply all wallpapers at once using feh
    if [[ ${#wallpaper_args[@]} -gt 0 ]]; then
        feh --no-fehbg "${wallpaper_args[@]}" &
    fi
else
    echo "Wallpaper config file is missing or empty."
fi

# Loads the login sound and plays a login sound at login
source /home/$USER/.config/bspwm/scripts/OpenFlexOS_Sounds.sh
if [[ ! -z "$login_sound" ]]; then
    mpv --no-video "${sounds_dir}${login_sound}" &
fi

# Starts a script to monitor battery, when low it gives a warrning or hibernates the system
/home/$USER/.config/qtile/scripts/OpenFlexOS_BatteryHibernate.sh &

pgrep -x sxhkd  > /dev/null || sxhkd -c /home/chris/.config/bspwm/sxhkdrc &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         2
#bspc config window_gap          12
bspc config window_gap          30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc node -t floating

bspc rule -a zenity \
     state=floating sticky=on follow=off focus=on \

bspc rule -a Galculator \
     state=floating sticky=on follow=off focus=on \     

bspc rule -a tilda \
     state=floating sticky=on follow=off focus=on \     